### PR TITLE
Fixed error when writing to db

### PR DESCRIPTION
**Pull request by jontstaz**
Script originally failed when handling duplicate TX IDs.

### CODE REVIEW

**Comment by EtWnn** [comment]
Thanks a lot for taking the time to submit a PR! 

However, I have two comments:

- First, I believed that the transaction ID for deposit is unique. So we have to investigate if the error you got was because it is not, or if it is because the library tried to save twice the same deposit. Depending on the case, the resolution is different.
(we can discuss that in the issue)

- Second, I will write the proper guidelines for PR, but I would prefer if you could create a specific branch with a fix and then create a PR from your branch to the develop branch of this repo

I will close this PR without merging because of the 2 points above

**Comment by EtWnn** [comment]
guidelines: https://github.com/EtWnn/BinanceWatch/blob/develop/CONTRIBUTING.md

**Comment by jontstaz** [comment]
Sorry mate, didn't see the contribution rules!!

**Comment by EtWnn** [comment]
The fault is on me, your PR reminded me that I forgot to upload them :sweat_smile:

**Pull request closed without merging**
